#include "notes.h"

typedef struct {
  uint16_t freq;
  uint16_t dur;
} Note;

const Note melody[] PROGMEM = {
  {NOTE_E4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_F4,  QUARTER}, {NOTE_G4,  QUARTER},
  {NOTE_G4,  QUARTER}, {NOTE_F4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_D4,  QUARTER},
  {NOTE_C4,  QUARTER}, {NOTE_C4,  QUARTER}, {NOTE_D4,  QUARTER}, {NOTE_E4,  QUARTER},
  {NOTE_E4,  HALF},    {NOTE_D4,  QUARTER}, {NOTE_D4,  HALF},

  {NOTE_E4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_F4,  QUARTER}, {NOTE_G4,  QUARTER},
  {NOTE_G4,  QUARTER}, {NOTE_F4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_D4,  QUARTER},
  {NOTE_C4,  QUARTER}, {NOTE_C4,  QUARTER}, {NOTE_D4,  QUARTER}, {NOTE_E4,  QUARTER},
  {NOTE_D4,  HALF},    {NOTE_C4,  QUARTER}, {NOTE_C4,  HALF},

  {NOTE_D4,  QUARTER}, {NOTE_D4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_C4,  QUARTER},
  {NOTE_D4,  QUARTER}, {NOTE_E4,  EIGHTH},  {NOTE_F4,  EIGHTH},  {NOTE_E4,  QUARTER},
  {NOTE_C4,  QUARTER}, {NOTE_D4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_C4,  QUARTER},
  {NOTE_D4,  QUARTER}, {NOTE_E4,  EIGHTH},  {NOTE_F4,  EIGHTH},  {NOTE_E4,  QUARTER},
  {NOTE_C4,  HALF},

  {NOTE_G4,  QUARTER}, {NOTE_G4,  QUARTER}, {NOTE_F4,  QUARTER}, {NOTE_E4,  QUARTER},
  {NOTE_D4,  QUARTER}, {NOTE_D4,  QUARTER}, {NOTE_E4,  QUARTER}, {NOTE_C4,  QUARTER},
  {NOTE_D4,  QUARTER}, {NOTE_E4,  EIGHTH},  {NOTE_F4,  EIGHTH},  {NOTE_E4,  QUARTER},
  {NOTE_C4,  HALF},    {NOTE_REST, HALF}
};

#define MELODY_LEN (sizeof(melody)/sizeof(melody[0]))
